#!/usr/bin/env bash
# This script installs nginx and configures it to return "Holberton School"

sudo apt-get update -y
sudo apt-get install nginx -y

sudo mkdir -p /var/www/html
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

sudo service nginx restart
