#!/usr/bin/env bash
# Install nginx and configure root page with Holberton School

sudo apt-get update -y
sudo apt-get install nginx -y

sudo mkdir -p /var/www/html
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

sudo service nginx restart
